name: Frontend CI with Test Report

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests with coverage
        run: |
          cd frontend
          npm test -- --coverage --watchAll=false

      - name: Read coverage summary
        id: coverage
        run: |
          SUMMARY=$(node -e "
            const summary = require('./frontend/coverage/coverage-summary.json').total;
            console.log(
              'Statements: ' + summary.statements.pct + '% (' + summary.statements.covered + '/' + summary.statements.total + ')\\n' +
              'Branches:   ' + summary.branches.pct + '% (' + summary.branches.covered + '/' + summary.branches.total + ')\\n' +
              'Functions:  ' + summary.functions.pct + '% (' + summary.functions.covered + '/' + summary.functions.total + ')\\n' +
              'Lines:      ' + summary.lines.pct + '% (' + summary.lines.covered + '/' + summary.lines.total + ')'
            );
          ")
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post coverage as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-coverage
          message: |
            ✅ All tests passed!
            🧪 Test Coverage Summary:
            ```
            ${{ steps.coverage.outputs.summary }}
            ```
