name: Frontend CI with Test Report

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests with coverage
        run: |
          cd frontend
          npm test -- --coverage --watchAll=false

      - name: Read coverage summary
        id: coverage
        run: |
          SUMMARY=$(node -e "
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('frontend/coverage/coverage-summary.json'));
            const total = data.total;
            console.log(
              'Statements: ' + total.statements.pct + '%\\n' +
              'Branches: ' + total.branches.pct + '%\\n' +
              'Functions: ' + total.functions.pct + '%\\n' +
              'Lines: ' + total.lines.pct + '%'
            );
          ")
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post test coverage as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-coverage
          message: |
            ✅ All tests passed!
            🧪 Test Coverage Summary:
            ```
            ${{ steps.coverage.outputs.summary }}
            ```
